# Check the web performace using
# lighthouse ci
# allow to show the page result for seo, performace, compatibility
#
# ******** NOTE *********
# Lighthouse only check your web result and platform

name: Lighthouse

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish"]
    types:
      - completed
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write

jobs:
  lighthouse:
    name: Lighthouse testing
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Audit url using lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            ${{ secrets.LIGHTHOUSE_AUDIT_DOMAINS }}
          uploadArtifacts: true
          temporaryPublicStorage: true
